# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 16:51
from __future__ import unicode_literals

import django_atlassian.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlassian', '0002_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlassian.Project')),
            ],
        ),
    ]
