# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-15 18:17
from __future__ import unicode_literals

import django_atlassian.models.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlassian', '0003_component_content_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_date',
            field=models.DateField(default=datetime.date(2015, 2, 24)),
            preserve_default=False,
        ),
    ]
