# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-28 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_atlassian.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('atlassian', '0004_auto_20180915_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
