version: "3"

services:
  app:
    restart: always
    build: .
    ports:
        - "9000:8000"
    links:
      - db:db
      - redis:redis
    volumes:
      - .:/app
    env_file: .env.local
    tty: true
    stdin_open: true
    command: sh -c "/usr/bin/supervisord -n"
    container_name: atlassian-addon-app
    networks:
      - default
      - web_fluendo_default

  db:
    restart: always
    image: postgres:latest
    volumes:
      - db:/var/lib/postgresql/data/
    env_file: .env.local
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWD}
    container_name: ${DB_HOST}

  redis:
    restart: always
    image: redis:latest
    volumes:
      - redis:/data
    env_file: .env.local
    container_name: ${REDIS_HOST}

volumes:
    redis:
    db:

networks:
  default:
    driver: bridge
  web_fluendo_default:
    external: true
