version: "3"
services:
  app:
    restart: always
    image: 589180693493.dkr.ecr.us-east-1.amazonaws.com/atlassian_addon:latest
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    depends_on:
      - redis
    logging:
      driver: awslogs
      options:
        awslogs-group: fargate_atlassianaddon
        awslogs-region: us-east-1
        awslogs-stream-prefix: f_atlassianaddon
    env_file: .env.prod
    command: sh -c "/usr/bin/supervisord -n"
    container_name: atlassian-addon-app
  redis:
    restart: always
    image: redis:alpine
    ports:
      - '6379:6379'
    command: sh -c "hostname && /usr/local/bin/redis-server --bind localhost --port 6379"
    logging:
      driver: awslogs
      options:
        awslogs-group: fargate_atlassianaddon
        awslogs-region: us-east-1
        awslogs-stream-prefix: f_atlassianaddon
    env_file: .env.prod
    container_name: atlassian-addon-redis