version: "3"
services:
  web:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports: 
     - "8002:8000"
     - "3002:3002"
    volumes: 
     - .:/app
    env_file: web.env
    depends_on: 
     - db_addon
     - redis_addon
    tty: true
    stdin_open: true
  
  redis_addon:
    restart: always
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379" 
    volumes: 
      - jiraddon_redis:/data
    tty: true
    stdin_open: true

  db_addon:
    restart: always
    image: postgres:11-alpine
    environment: 
      POSTGRES_DB: ${DB_NAME} 
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWD}
    ports:
      - "${PG_PORT}:5234"
    volumes: 
      - jiradb:/var/lib/postgresql/data
    tty: true
    stdin_open: true

volumes: 
  jiraddon_redis:
  jiradb:

networks: 
  default:
    external:
     name: webfluendo_default