version: "3"
services:
  addon:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    ports:
        - "9000:8000"
    external_links:
        - web-fluendo_fluendo_1:fluendo
        - web-fluendo_db_1:db
        - web-fluendo_redis_1:redis
    volumes:
        - .:/app
        - ../django-atlassian/django_atlassian:/app/django_atlassian
    tty: true
    stdin_open: true

networks:
  default:
    external:
      name: web-fluendo_default
