# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2020-10-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    
    def set_my_defaults(apps, schema_editor):
        SecurityContext = apps.get_model('django_atlassian', 'SecurityContext')
        for sc in SecurityContext.objects.all():
            if sc.host.endswith('wiki'):
                sc.product_type = 'confluence'
            else:
                sc.product_type = 'jira'
            sc.save()
    
    def reverse_func(apps, schema_editor):
        pass


    dependencies = [
        ('django_atlassian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycontext',
            name='product_type',
            field=models.CharField(null=True, max_length=512)
        ),
        migrations.RunPython(set_my_defaults, reverse_func),
        migrations.AlterField(
            model_name='securitycontext',
            name='product_type',
            field=models.CharField(null=False, max_length=512)
        ),
    ]
