# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-06-26 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_atlassian', '0002_securitycontext_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitycontext',
            name='oauth_client_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
